server:
  port: 8000

#配置数据源
spring:
  datasource:
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 初始化连接大小
        initial-size: 5
        # 最小空闲连接数
        min-idle: 5
        max-active: 20
        max-wait: 30000
        # 可关闭的空闲连接间隔时间
        time-between-eviction-runs-millis: 60000
        # 配置连接在池中的最小生存时间
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select '1'
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
      primary: data_eladmin_1
      datasource:
        data_eladmin_1:
#          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: root
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://localhost:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        data_eladmin_2:
          #          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: root
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://localhost:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true

  jackson:
    time-zone: GMT+8

  redis:
    #数据库索引
    database: 0
    host: 192.168.188.12
    port: 6379
    password: 1314hemiao520
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  #  expiration: 60000
  auth:
    # 授权路径
    login: /login
    # 路径
    signin: /signin
    # 获取用户信息
    account: /info


#七牛云
qiniu:
  # 文件大小 /M
  max-size: 5

#验证码有效时间/分钟
code:
  expiration: 5

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml